spring.profiles.active=prod

spring.application.name=portal
spring.main.banner-mode=off

logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.hibernate.validator=WARN
logging.level.org.springframework.boot=WARN
logging.level.org.springframework.data=WARN
logging.level.org.springframework.orm=WARN