
hispatec.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
hispatec.jdbc.url=jdbc:sqlserver://192.184.2.252:1433;databaseName=ERPHispatec;TrustServerCertificate=false;encrypt=false
hispatec.jdbc.username=ruben.martinez
hispatec.jdbc.password=Q+Tah&689SxR

hispatec.hibernate.default_schema=dbo

hispatec.jpa.show-sql=false
hispatec.jpa.hibernate.ddl-auto=none
hispatec.jpa.properties.hibernate.format_sql=true

