
req.datasource.driver-class-name=org.postgresql.Driver
req.jdbc.url=jdbc:postgresql://192.184.2.248:65432/RD
req.jdbc.username=postgres
req.jdbc.password=Kud3006927

req.hibernate.default_schema=public

req.jpa.show-sql=false
req.jpa.hibernate.ddl-auto=none
req.jpa.properties.hibernate.format_sql=true

