
req.datasource.driver-class-name=org.postgresql.Driver
req.jdbc.url=jdbc:postgresql://172.16.50.9:5432/RD
req.jdbc.username=postgres
req.jdbc.password=D4t4b4se.AGZ

req.hibernate.default_schema=public

req.jpa.show-sql=false
req.jpa.hibernate.ddl-auto=none
req.jpa.properties.hibernate.format_sql=true

